- common/test0.js
> javascriptの外部ファイル化テスト

- common/test.js
> javascript外部ファイル化テスト

- include/footer.php
> フッターのコピーライトの年数を2016に変更

- lawyer/_notes/dwsync.xml
- lawyer/matuehitomi.html
- lawyer/matueyoriatu.html
弁護士紹介の代表と顧問に、得意分野の相続追加。顧問から建築不動産トルツメ
> 弁護士紹介の代表と顧問に、得意分野の相続追加。顧問から建築不動産トルツメ

- business/divorce/_notes/dwsync.xml
- business/divorce/index.html
離婚インデックスのスマホのグローバルメニュー開かないバグ修正
> 離婚インデックスのスマホのグローバルメニュー開かないバグ修正

- intro/lp2/index.html
> LP2にGSタグ設置

- business/divorce/case/_notes/dwsync.xml
- business/divorce/case/mediation/_notes/dwsync.xml
- business/enquete/index.html
> お客様の声のレーダーチャートに、y軸目盛りを追加

- business/enquete/_notes/dwsync.xml
- business/enquete/index.html
> お客様の声のレーダーチャートの線を４段階に変更

- templates/_notes/dwsync.xml
- templates/input.html
> 問い合わせフォームの電話番号入力を修正

- business/enquete/index.html
お客様の声のレーダーチャートのツールチップをlabelだけ表示に変更
> お客様の声のレーダーチャートのツールチップをlabelだけ表示に変更

- common/css/_notes/dwsync.xml
- common/css/dream.css
> トップページのh2のcssスタイル編集。

- business/divorce/case/lawsuit/case043.html
- business/divorce/case/lawsuit/case044.html
- business/divorce/case/lawsuit/case045.html
- business/divorce/case/lawsuit/case046.html
- business/divorce/case/lawsuit/case047.html
- business/divorce/case/lawsuit/case048.html
- business/divorce/case/lawsuit/case049.html
- business/divorce/case/lawsuit/case050.html
- business/divorce/case/lawsuit/case051.html
- business/divorce/case/lawsuit/case052.html
- business/divorce/case/lawsuit/case053.html
- business/divorce/case/lawsuit/case054.html
- business/divorce/case/lawsuit/case055.html
- business/divorce/case/lawsuit/case076.html
- business/divorce/case/lawsuit/case077.html
- business/divorce/case/lawsuit/case079.html
- business/divorce/case/lawsuit/case084.html
- business/divorce/case/lawsuit/case086.html
- business/divorce/case/lawsuit/case088.html
> Dir /case/lawsuit0901

- business/divorce/case/ohter/case060.html
- business/divorce/case/ohter/case061.html
- business/divorce/case/ohter/case062.html
- business/divorce/case/ohter/case063.html
- business/divorce/case/ohter/case064.html
- business/divorce/case/ohter/case065.html
- business/divorce/case/ohter/case066.html
- business/divorce/case/ohter/case067.html
- business/divorce/case/ohter/case068.html
- business/divorce/case/ohter/case069.html
- business/divorce/case/ohter/case070.html
- business/divorce/case/ohter/case071.html
- business/divorce/case/ohter/case072.html
- business/divorce/case/ohter/case073.html
- business/divorce/case/ohter/case074.html
- business/divorce/case/ohter/case075.html
- business/divorce/case/ohter/case078.html
- business/divorce/case/ohter/case082.html
- business/divorce/case/ohter/case083.html
- business/divorce/case/ohter/case085.html
- business/divorce/case/ohter/case087.html
> Dir /case/other

- business/divorce/money/child_support.html
- business/divorce/money/compensation.html
- business/divorce/money/distribution.html
- business/divorce/money/enforcement.html
- business/divorce/money/loan.html
- business/divorce/money/notification.html
- business/divorce/money/pension.html
/business/divorce/money/
離婚とお金ページ_SEO対策
> Dir /divorce/money

- business/divorce/dv/index.html
> dvインデックスのキーワードを修正

- index.html
> TOPpage 新着情報編集

- intro/lp4/index.html
- intro/lp4/lp4-sidecolumn.css
- intro/lp4/lp4-style.css
> ランディングページ（LP4）のスマホ版デザイン完成。

- intro/lp4/index.html
- intro/lp4/lp4-style.css
> lp4のheaderにロゴ追加。

- intro/lp4/index.html
- intro/lp4/lp4-style.css
> lp4に、copyrightを追加。

- business/divorce/immorality/index.html
> 不倫でお悩みの方へページの動画にタイトルを個別に入れ直し。

- index.html
> トップページのcanonicalをhttpsに変更

- business/divorce/index.html
> 離婚インデックスのスタイルの絶対パスを相対パスに変更

- business/enquete/index.html
> お客様の声にcanonical入れ。ルート相対パス化

- common/css/base.css
- common/css/contact.css
- common/css/fee.css
- common/css/media.css
- common/css/second.css
> スタイルシートのurlをルート相対パスに編集

- business/divorce/index.html
> 離婚インデックスをhttpsが正規に認証されるように修正

- business/building/index.html
> 建築インデックスを正規にssl認証されるように修正

- business/building/case/case001.html
- business/building/case/case002.html
- business/building/case/case003.html
- business/building/case/case004.html
- business/building/case/case005.html
- business/building/case/case006.html
- business/building/case/case007.html
- business/building/case/case008.html
- business/building/case/case009.html
- business/building/case/index.html
> 建築の解決事例をssl認証が正規にされるように修正

- business/building/adviser/index.html
> 建築の顧問契約をssl認証が正規に認証されるよう修正

- business/building/seminar/index.html
- business/building/seminar/seminar_20141016.html
- business/building/seminar/seminar_20141211.html
> 建築のセミナーでsslが正規に認証されるよう修正

- business/building/blog/blog_template.html
- business/building/blog/index.html
- business/building/blog/land-trading.html
- business/building/blog/loan-terms.html
- business/building/blog/neighboring-relationship-trouble.html
- business/building/blog/protect-unpaid-reward.html
> 建築のブログをsslで正規認証されるよう修正

- templates/confirm.html
- templates/input.html
- templates/thanks.html
> 問い合わせをssl認証が正規にされるように修正

- business/building/adviser/index.html
- business/building/blog/index.html
- business/building/case/index.html
- business/building/index.html
- business/building/seminar/index.html
- business/enquete/index.html
- fee/index.html
- fee/why/kyougisyo.html
- lawyer/index.html
> 弁護士費用をsslで正規に認証されるように修正

- business/divorce/index.html
離婚インデックスのcanonicalからindex.htmlをトルツメ
> 離婚インデックスのcanonicalからindex.htmlをトルツメ

- flow/index.html
- flow/lawyer_merit.html
> ご相談の流れをssl認証されるように修正

- office/index.html
- office/vision.html
> 事務所紹介をsslで正規認証されるよう修正

- business/divorce/rikondojyo/01.html
- business/divorce/rikondojyo/02.html
- business/divorce/rikondojyo/03.html
- business/divorce/rikondojyo/04.html
- business/divorce/rikondojyo/05.html
- business/divorce/rikondojyo/06.html
- business/divorce/rikondojyo/07.html
- business/divorce/rikondojyo/index.html
> 離婚道場をsslで正規認証するように修正

- business/divorce/rikondojyo/index.html
- business/divorce/succession/index.html
- business/divorce/succession/succesion_case.html
- business/divorce/succession/succesion_gib.html
- business/divorce/succession/succesion_j.html
- business/divorce/succession/succesion_reserved.html
- business/divorce/succession/succesion_who.html
- business/divorce/succession/succesionj.html
- office/index.html
> 相続をsslで正規認証するように修正

- business/divorce/morahara/index.html
> /morahara/index.html

- business/divorce/money/child_support.html
- business/divorce/money/compensation.html
- business/divorce/money/distribution.html
- business/divorce/money/enforcement.html
- business/divorce/money/index.html
- business/divorce/money/loan.html
- business/divorce/money/notification.html
- business/divorce/money/pension.html
> Dir /money

- business/divorce/dv/dv_men.html
- business/divorce/women/index.html
- business/divorce/women/women_good.html
- business/divorce/women/women_mainstay.html
- business/divorce/women/women_vintage-year.html
> 女性の離婚をsslで正規認証するように修正

- business/divorce/immorality/immorality_men.html
- business/divorce/immorality/immorality_women.html
- business/divorce/immorality/index.html
/bussiness/divorce/immorality/
SEO対策,title,テキスト編集
> Dir /immorality

- business/divorce/index.html
> 離婚インデックスのリンク記述法を修正

- business/divorce/child/change.html
- business/divorce/child/custody.html
- business/divorce/child/custody02.html
- business/divorce/child/habeas.html
- business/divorce/child/index.html
- business/divorce/child/visitation.html
/business/divorce/child/
SEO対策
> Dir /child

- intro/lp4/index.html
- intro/lp4/lp4-style.css
> lp4のsectionの区切りを修正

- include/header.php
> headerインクルードからheaderの追尾トルツメ

- intro/lp3/index.html
- intro/lp3/lp3.css
> lp3のフッターのスタイル崩れを修正

- intro/lp4/index.html
> lp4の代表画像のリンクパス修正

- intro/lp4/index.html
> lp4のindexの「別居」のURLを編集

- flow/lawyer_merit.html
/flow/lawyer_merit.html
title, meta情報の修正
> title, meta情報_修正

- business/divorce/succession/index.html
- business/divorce/succession/succesion_case.html
- business/divorce/succession/succesion_gib.html
- business/divorce/succession/succesion_j.html
- business/divorce/succession/succesion_reserved.html
- business/divorce/succession/succesion_who.html
bussiness/divorce/succession/
title, meta情報_編集
> Dir /succession

- include/global_nav.php
> メニューに相続に関する費用を追加

- divorce/index.html
- intro/lp4/index.html
lp4とdivorce/indexのpoint3の文言を修正
> lp4とdivorce/indexのpoint3の文言を修正

- divorce/styles/lp4-style.css
Divorce contents bekkyo responsive
> Divorce contents bekkyo responsive

- divorce/index.html
- divorce/styles/lp4-style.css
> divorceのstyle直がき部分を外部css化

- divorce/index.html
> divorceの淡路町ドリームの強みの４つ目の画像を変更

- divorce/index.html
- divorce/styles/globalmenu.css
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> divoreのh2のデザイン変更

- divorce/contents/separate.html
- divorce/index.html
- divorce/styles/footer.css
> Divorce footer

- business/enquete/index.html
> アンケートindexの男性画像と女性画像の間違い修正

- intro/building/index.html
> 建築LPの個人の場合の料金記載をトルツメ

- divorce/index.html
- divorce/styles/lp4-style.css
> 離婚特設ページトップのデザイン変更

- divorce/index.html
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> 離婚特設ページインデックスの改善

- divorce/case/index.html
- divorce/js/refine-search.js
- divorce/js/refine.css
- divorce/styles/contents-style.css
> divorceの解決事例に、フィルター機能を導入

- divorce/js/refine.css
> divorceの解決事例のフィルターボタンのデザイン入れ

- divorce/case/index.html
- divorce/index.html
- divorce/js/refine.css
> divorceの解決事例のデザイン修正、一部事例流し込み

- divorce/case/index.html
- divorce/index.html
- divorce/styles/footer.css
> footerデザイン変更

- divorce/contents/separate.html
> divorceの別居が意味するものページのテンプレ変更

- divorce/case/index.html
> divorceの解決事例に不倫の事例を見本のためにアップ

- divorce/case/index.html
- divorce/styles/lp4-sidecolumn.css
> divorceの解決事例にサンプル追加

- divorce/index.html
> divorceのトップページのサイドバナーを修正

- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> divorceのサイドバナー等のスタイルを変更

- divorce/index.html
- divorce/styles/globalmenu.css
> divorceのグローバルナビのホバー時のデザイン変更

- divorce/case/index.html
- divorce/contents/actual-compensation.html
- divorce/contents/first-consultation.html
- divorce/contents/merit.html
- divorce/contents/separate.html
- divorce/index.html
- divorce/styles/globalmenu.css
- divorce/styles/lp4-style.css
> divorceのグローバルメニューのaタグ位置変更

- divorce/index.html
- divorce/styles/footer.css
- divorce/styles/globalmenu.css
- divorce/styles/lp4-style.css
> レスポンシブデザイン修正

- divorce/styles/contents-style.css
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
divorceの枠線の肌色を灰色に変更。下層ページのレスポンシブ修正
> divorceの枠線の肌色を灰色に変更。下層ページのレスポンシブ修正

- divorce/index.html
- divorce/styles/lp4-style.css
> divorceトップの記事中に問い合わせボタン追加

- business/building/seminar/index.html
> 建築のセミナー情報の終了してるやつに終了を記載

- common/css/second.css
- include/header.php
> 年末年始情報をヘッダーに入れた

- include/header.php
> 年末年始の休業情報トルツメ

- divorce/index.html
- divorce/styles/lp4-style.css
> divorceを藤本さん新デザイン案前に戻す

- divorce-prototype/index.html
- divorce-prototype/styles/bxslider.css
- divorce-prototype/styles/lp4-style.css
> divorce-prototypeのトップデザイン変更

- divorce-prototype/case/index.html
> 解決事例インデックスに事例追加

- divorce-prototype/index.html
- divorce-prototype/styles/bxslider.css
- divorce-prototype/styles/globalmenu.css
- divorce-prototype/styles/lp4-style.css
> 離婚特設ページプロトタイプのデザインをUX重視で変更

- divorce-prototype/include/footer.php
- divorce-prototype/include/globalmenu.php
- divorce-prototype/include/sidecol-left.php
- divorce-prototype/index.html
- divorce-prototype/styles/footer.css
- divorce-prototype/styles/lp4-style.css
divorce-prototypeのトップページデザインの変更
> divorce-prototypeのトップページデザインの変更

- divorce-prototype/index.html
- divorce-prototype/styles/lp4-style.css
divorce-prototypeのindexのUX改善のために余白とった
> divorce-prototypeのindexのUX改善のために余白とった

- divorce-prototype/index.html
- divorce-prototype/styles/footer.css
- divorce-prototype/styles/lp4-style.css
> divorce-prototypeのデザイン微調整

- divorce/index.html
- divorce/styles/lp4-style.css
> divorceの代表メッセージのデザイン修正

- divorce/index.html
- divorce/styles/lp4-style.css
> divorceトップのリンクボタン変更

- divorce/index.html
> divorceのお客様の声に男性の声を追加

- divorce/lawyer/index.html
- divorce/lawyer/irie-hideko.html
- divorce/lawyer/matsue-hitomi.html
- divorce/lawyer/matsue-yoriatu.html
- divorce/lawyer/miyoshi-ryoko.html
- divorce/lawyer/shimizu-risei.html
- divorce/lawyer/ujiie-daisuke.html
- divorce/lawyer/yamashita-hiromi.html
- divorce/styles/lawyer-introduction.css
> divorceに弁護士紹介ページ作成

- divorce/fee/index.html
- divorce/styles/contents-style.css
- divorce/styles/fee.css
> divorceに弁護士費用ページを追加（noindex）

- business/divorce/case/index.html
> 現行の解決事例のURLミスを修正

- 404.html
> 404のデザイン崩れ修正

- divorce/media/index.html
- divorce/office/index.html
- divorce/public/index.html
- divorce/sitemap/index.html
メディア情報、当法人について、プライバシーポリシー、サイトマップ
上記ページ表示用ディレクトリアップ
> 追加ページ用ディレクトリアップ

- divorce/include/footer.php
> footerのcopyright変更

- divorce/include/footer.php
- divorce/include/sidecol-left.php
> 解決事例を解決実績に変更

- divorce/styles/contents-style.css
> divorceのサイトマップのデザイン崩れ修正

- divorce/styles/footer.css
- divorce/styles/lp4-style.css
> レスポンシブ時のデザイン崩れ修正

- divorce/index.html
- divorce/styles/lp4-style.css
divorceトップの代表メッセージを最新の藤本さん案に編集
> divorceトップの代表メッセージを最新の藤本さん案に編集

- divorce/contents/message.html
> 代表メッセージのパンくず等修正

- divorce/case/index.html
> 解決事例のパンくず修正

- divorce/contents/merit.html
> 弁護士に相談するメリットのパンくず・画像等を修正

- divorce/contents/first-consultation.html
> 初めての離婚相談のパンくず・画像修正

- divorce/contents/actual-compensation.html
> 慰謝料のホントのパンくず・画像変更

- divorce/contents/actual-compensation.html
> 慰謝料のホントのh1より上にある文言削除

- divorce/contents/factor.html
> 離婚原因のパンくず画像修正

- divorce/contents/flow.html
- divorce/contents/type/index.html
> 離婚手続き系のパンくず・画像

- divorce/include/sidecol-left.php
> 左カラムのリンク修正を再度なおす

- divorce/contents/qa/index.html
- divorce/contents/qa/qa_child.html
- divorce/contents/qa/qa_compensation.html
- divorce/contents/qa/qa_concubinage.html
- divorce/contents/qa/qa_distribution.html
- divorce/contents/qa/qa_factor.html
- divorce/contents/qa/qa_fee.html
- divorce/contents/qa/qa_method.html
- divorce/contents/qa/qa_separation.html
> divorceのQ＆Aページの画像FIX

- divorce/case/index.html
- divorce/js/refine-search.js
- divorce/styles/contents-style.css
- divorce/styles/refine.css
> divorceの解決事例のSPデザインFIX

- divorce/styles/refine.css
> divorceの解決事例のパソコン版のデザインFIX

- index.html
> トップページの最新情報を更新

- divorce/case/case001.html
- divorce/styles/contents-style.css
> divorceに解決事例1作成

- divorce/styles/contents-style.css
> コンフリクトに生じたバグ修正

- divorce/include/sidecol-left.php
> divorceの左カラムの先祖返りを修正

- divorce/include/sidecol-left.php
> 左カラムのMY弁護士のリンクを別タブ表示に変更

- divorce/include/sidecol-left.php
divorceの左カラムのMY弁護士のリンクに外部リンクを表すアイコン入れた。
> divorceの左カラムのMY弁護士のリンクに外部リンクを表すアイコン入れた。

- divorce/media/index.html
divorceのメディア実績の先祖返り修正＆外部リンクにnofollow＆Fontawesome入れ
> divorceのメディア実績の先祖返り修正＆外部リンクにnofollow＆Fontawesome入れ

- business/building/seminar/index.html
> 建築セミナーの構造化マークアップを修正

- divorce/contents/message.html
divorceの代表メッセージのh1から余分な部分をトルツメ
> divorceの代表メッセージのh1から余分な部分をトルツメ

- divorce/contents/message.html
> divorceの代表メッセージのh1を修正

- divorce/index.html
- divorce/styles/lp4-sidecolumn.css
> Temp020401

- divorce/styles/contents-style.css
- divorce/styles/footer.css
> Temp030402

- include/header.php
includeのheaderの上にGAのトラッキングコードを入れた。
> includeのheaderの上にGAのトラッキングコードを入れた。

- include/footer.php
- include/header.php
- templates/confirm.html
- templates/input.html
- templates/thanks.html
> GAのコンバージョンタグの修正

- divorce/lawyer/irie-hideko.html
- divorce/lawyer/matsue-hitomi.html
> divorceの弁護士紹介の代表と入江さんページをリライト

- divorce/index.html
> divorceトップの代表メッセージを修正

- divorce/styles/footer.css
> divorceのフッターのグーグルマップのデザインを変更

- intro/lp2/index.html
> lp2にトラッキングタグ入れ＆電話発信の計測タグも入れた

- business/divorce/index.html
- business/divorce/rikon/cheat.html
- business/divorce/rikon/custody.html
- business/divorce/rikon/distribution-of-property.html
- intro/kenchiku-seminar/index.html
- intro/lp3/index.html
> 電話番号のトラッキングタグ入ってないところにタグ入れた

- divorce/contents/type/arbitration.html
> divorceのコンテンツの調停離婚に内部リンクを入れた。

- divorce/contents/money/notification.html
divorceの婚姻費用ページの外部リンクにnofollow入れた。
> divorceの婚姻費用ページの外部リンクにnofollow入れた。

- divorce/styles/globalmenu.css
> divorceのグローバルナビのホバー時の色を変更

- divorce/contents/money/child_support.html
- divorce/contents/money/distribution.html
- divorce/contents/money/enforcement.html
- divorce/contents/money/notification.html
- divorce/contents/money/pension.html
- divorce/contents/money/real_estate.html
/divorce/contents/money/
ディレクトリ以下に内部リンク、関連リンク追加
> 内部リンク、関連リンク追加

- divorce/include/header.php
- divorce/index.html
- divorce/styles/lp4-style.css
> divorceのスマホのヘッダーのデザインをfix

- divorce/styles/lp4-style.css
> divorceのヘッダーのデザイン編集

- divorce/styles/drawer-change.css
divorceのスタイルシートにハンバーガーメニューのスタイルシート作成
> divorceのスタイルシートにハンバーガーメニューのスタイルシート作成

- divorce/styles/drawer-change.css
- divorce/styles/lp4-style.css
> divorceのハンバーガーメニューのデザインを修正

- divorce/index.html
- divorce/styles/drawer-change.css
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> divorceトップのデザインを修正（プロ感を出した）

- divorce/styles/contents-style.css
> divorce下層ページのスマホ時の崩れを修正

- divorce/styles/contents-style.css
- divorce/styles/lp4-style.css
> divorce下層ページのデザイン修正

- divorce/contents/flow.html
> divorceのflowのグロナビの残りをトルツメ

- divorce/include/header.php
> divoeceのheaderにアナリティクスを入れた

- divorce/case/index.html
- divorce/styles/refine.css
> 解決事例のスマホ時のボタンのデザインかぶりを修正

- divorce/include/sidecol-left.php
- divorce/styles/bxslider.css
- divorce/styles/contents-style.css
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> divorceにタブレット対応のデザイン追加

- .htaccess
> htaccessをgit管理

- divorce/case/index.html
- divorce/styles/contents-style.css
> divorceの解決事例インデックスの崩れを修正

- divorce/include/footer.php
- divorce/include/sidecol-left.php
divorceのMY弁護士へのリンクからnofollow外した。（自社メディアなので）
> divorceのMY弁護士へのリンクからnofollow外した。（自社メディアなので）

- index.html
トップページの最新情報に離婚特設ページをリリースしたことを告知した。
> トップページの最新情報に離婚特設ページをリリースしたことを告知した。

- divorce/case/index.html
- divorce/contents/domestic-violence.html
- divorce/contents/type/adjudicated.html
- divorce/contents/type/arbitration.html
- divorce/contents/type/consent.html
- divorce/contents/type/judgement.html
- divorce/fee/index.html
- divorce/lawyer/index.html
- divorce/lawyer/matsue-yoriatu.html
- divorce/lawyer/miyoshi-ryoko.html
- divorce/lawyer/shimizu-risei.html
- divorce/lawyer/ujiie-daisuke.html
- divorce/lawyer/yamashita-hiromi.html
- divorce/media/index.html
- divorce/office/index.html
- divorce/public/index.html
- divorce/sitemap/index.html
noindexの二重引用符が正常に識別されずに、googleにインデックスされてしまっていたので、二重引用符を正しいものに書き換えた。
> noindexの二重引用符を正常なものに変更

- divorce/contents/domestic-violence.html
- divorce/contents/factor.html
- divorce/contents/flow.html
- divorce/contents/qa/qa_child.html
- divorce/contents/qa/qa_compensation.html
- divorce/contents/qa/qa_distribution.html
- divorce/contents/qa/qa_factor.html
- divorce/contents/qa/qa_fee.html
- divorce/contents/qa/qa_method.html
- divorce/contents/qa/qa_separation.html
- divorce/contents/type/adjudicated.html
- divorce/contents/type/arbitration.html
- divorce/contents/type/consent.html
- divorce/contents/type/judgement.html
内部リンク、関連リンク追加
-->typeディレクトリ、domestic-violence.html,factor.html,flow.html
関連リンクスペル修正
-->qaディレクトリ
> Inner link

- intro/lp2/lp-inheritance.html
> 相続LPにGA入れた。

- .htaccess
既存の別居ページを離婚特設ページの別居ページにリダイレクトした。
> 既存の別居ページを離婚特設ページの別居ページにリダイレクトした。

- divorce/case/index.html
divorceの解決事例indexのmetaにnofollowを入れた。
> divorceの解決事例indexのmetaにnofollowを入れた。

- divorce/styles/contents-style.css
> divorceの解決事例のリストのデザイン崩れを修正

- divorce/include/globalmenu.php
- divorce/intro/index.html
> divorce内にlp2を移植した。

- divorce/styles/globalmenu.css
divorceのグロナビのデザイン修正（intro追加に伴い）
> divorceのグロナビのデザイン修正（intro追加に伴い）

- sitemap.xml
> sitemap.xmlを更新した。

- divorce/case/index.html
離婚特設ページの解決事例インデックスからnofollowをトルツメした。
> 離婚特設ページの解決事例インデックスからnofollowをトルツメした。

- divorce/contents/separate.html
- divorce/include/contents-below-cta.php
- divorce/include/globalmenu.php
- divorce/styles/contents-style.css
離婚特設ページの別居ページの下部にLPに飛ばすバナーを設置した。
> 離婚特設ページの別居ページの下部にLPに飛ばすバナーを設置した。

- divorce/cta-test/separate.html
- divorce/include/cta_separate.php
> Contents cta

- divorce/contents/separate.html
- divorce/include/head.php
- divorce/include/social-button.php
- divorce/styles/social-button.css
> divorceの別居ページにソーシャルボタンを入れた。

- divorce/lawyer/index.html
- divorce/lawyer/irie-hideko.html
- divorce/lawyer/matsue-hitomi.html
- divorce/lawyer/matsue-yoriatu.html
- divorce/lawyer/miyoshi-ryoko.html
- divorce/lawyer/shimizu-risei.html
- divorce/lawyer/ujiie-daisuke.html
- divorce/lawyer/yamashita-hiromi.html
divorceの弁護士紹介ページにソーシャルボタンを入れた。
> divorceの弁護士紹介ページにソーシャルボタンを入れた。

- .htaccess
- divorce/contents/type/adjudicated.html
- divorce/contents/type/arbitration.html
- divorce/contents/type/consent.html
- divorce/contents/type/judgement.html
> divorceの離婚の種類をリダイレクト

- divorce/lawyer/index.html
divorceの弁護士一覧ページのソーシャルボタンを崩れによりトルツメ
> divorceの弁護士一覧ページのソーシャルボタンを崩れによりトルツメ

- common/css/contact.css
> 問い合わせフォームの確認ページのデザイン崩れ修正

- common/css/contact.css
> メール問い合わせ確認フォームのスマホ時のデザインを微調整

- common/css/base.css
> WACUL提案のデザインをbase.cssに追加

- common/css/top.css
> ワカルのグロナビのborder-bottomのサイズ調整

- common/css/business.css
> 下層ページのワカルのグロナビ修正のデザイン崩れを修正

- include/global_nav.php
- include/global_nav_ha.php
> ワカルのグロナビ内に潜む、h1を消すJSを修正

- divorce/index.html
- divorce/styles/lp4-style.css
> 離婚特集ページにh1入れた。

- templates/input.html
- templates/thanks.html
> GOLIRRA EFOのタグを挿入

- divorce/include/globalmenu.php
> divorceのグロナビを編集

- intro/building/index.html
- intro/index.html
- intro/lp2/lp-building.html
- intro/rikon-seminar/index.html
- templates/input.html
> 電話トラッキングコードを入れた。

- common/css/base.css
- divorce/contents/separate_test.html
- index_test2.html
トップページおよび別居ページに、ワカルから提案された改善案を反映したプロトタイプを作成した。
それに伴って、一部スタイル調整(base.css)。
> Wacul prototype

- common/css/base.css
- succession/index.html
- succession/succession_case.html
- succession/succession_legisration.html
- succession/succession_portions.html
- succession/succession_reserved.html
- succession/succession_target.html
- succession/succession_what.html
- succession/succession_who.html
> Succession dir

- divorce/include/contents-below-cta.php
- divorce/index.html
- divorce/styles/contents-style.css
- divorce/styles/globalmenu.css
- divorce/styles/lp4-sidecolumn.css
- divorce/styles/lp4-style.css
> 離婚特設ページのデザインを変更

- common/css/base.css
- index_test2.html
> WACUL提案、トップページのデザイン指摘箇所を修正

- divorce/contents/separate.html
- divorce/include/contents-below-cta.php
離婚特設ページの別居ページの記事下CTAの変更と、本文中に解決事例への導線入れた。
> 離婚特設ページの別居ページの記事下CTAの変更と、本文中に解決事例への導線入れた。

- common/css/base.css
- flow/index.html
トップページのワカル提案ボタンの色を明るくした。問い合わせの流れページにボタン追加
> トップページのワカル提案ボタンの色を明るくした。問い合わせの流れページにボタン追加

- intro/lp5/fee.html
- intro/lp5/index.html
> 相続LP(lp5)作成

- divorce/contents/merit.html
- divorce/styles/contents-style.css
> divorceの弁護士に相談するメリットの見た目を編集

- common/css/contact.css
- templates/confirm.html
- templates/input.html
> 問い合わせページのデザイン変更。項目を変更。

- .htaccess
ドメインを【https かつ wwwナシ】に統一するリダイレクト設定
> https301リダイレクト設定

- divorce/include/footer.php
- include/footer.php
> フッターのMY弁護士のリンクからSSLを取り除いた。

- common/css/base.css
- common/css/contact.css
- divorce/contents/actual-compensation.html
- divorce/contents/separate.html
- divorce/styles/contents-style.css
- index_test2.html
- templates/input.html
コンテンツにフォーム導線追加。問い合わせページのデザインを少し変更
> コンテンツにフォーム導線追加。問い合わせページのデザインを少し変更

- divorce/contents/separate.html
- divorce/styles/contents-style.css
> 別居ページの画像幅を修正

- common/css/base.css
- index_test2.html
トップページの「初めて離婚する方へ」のボタンのデザインを修正
> トップページの「初めて離婚する方へ」のボタンのデザインを修正

- divorce/contents/type/judgement.html
> /divorce/の審判ページのデッドリンクを取り除いた。

- divorce/contents/money/child_support.html
> 養育費ページのタイトルとh1を変更した。

- templates/confirm.html
問い合わせフォームの確認画面の項目の順序を、入力画面の順序に並び替えた。
> 問い合わせフォームの確認画面の項目の順序を、入力画面の順序に並び替えた。

- index_test2.html
> wacul デザインfix

- intro/lp-inheritance-tel-tracking/_notes/dwsync.xml
- intro/lp-inheritance-tel-tracking/index.html
> 相続LPに電話計測タグ入れたものを用意

- business/case-index.html
- business/divorce/case/index.html
> Remove http

- common/css/base.css
- index.html
- intro/building/index.html
- intro/index.html
- intro/kenchiku-seminar/index.html
- intro/kenchiku-seminar/thanks.html
- intro/lp3/index.html
- intro/lp4/index.html
- intro/lp5/fee.html
- intro/lp5/index.html
- intro/rikon-seminar/thanks.html
> httpからhttpsの変更に伴う絶対パスの削除

- google0ddf2ce1a457e954.html
httpsでのサーチコンソール用の所有権確認ファイル入れた。
> httpsでのサーチコンソール用の所有権確認ファイル入れた。

- sitemap.xml
> sitemap.xmlを更新した。（https用）
